/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately", "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.", "ru": "При сохранении настроек адаптера он сразу же перезапускается", "pt": "no adaptador de salvar reinicia com nova configuração imediatamente", "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config", "fr": "sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement", "it": "su save adapter si riavvia immediatamente con la nuova configurazione", "es": "en el adaptador de guardar se reinicia con nueva configuración de inmediato"},
    "adapter settings": {                            "en": "SmartVISU Settings",                              "de": "SmartVISU EInstellungen",                         "ru": "SmartVISU Settings",                              "pt": "SmartVISU Settings",                              "nl": "SmartVISU Settings",                              "fr": "SmartVISU Settings",                              "it": "SmartVISU Settings",                              "es": "SmartVISU Settings"},
    "serverPort": {                                  "en": "SmartVISU Server port",                           "de": "SmartVISU Server port",                           "ru": "SmartVISU Server port",                           "pt": "SmartVISU Server port",                           "nl": "SmartVISU Server port",                           "fr": "SmartVISU Server port",                           "it": "SmartVISU Server port",                           "es": "SmartVISU Server port"},
    "docRoot": {                                     "en": "Doc-Root (Path or empty for default)",            "de": "Doc-Root (Pfad oder leer für Default)",           "ru": "Doc-Root (Path or empty for default)",            "pt": "Doc-Root (Path or empty for default)",            "nl": "Doc-Root (Path or empty for default)",            "fr": "Doc-Root (Path or empty for default)",            "it": "Doc-Root (Path or empty for default)",            "es": "Doc-Root (Path or empty for default)"},
    "phpCgiPath": {                                  "en": "php-cgi (path or empty for default)",             "de": "php-cgi (Pfad oder leer für Default)",            "ru": "php-cgi (path or empty for default)",             "pt": "php-cgi (path or empty for default)",             "nl": "php-cgi (path or empty for default)",             "fr": "php-cgi (path or empty for default)",             "it": "php-cgi (path or empty for default)",             "es": "php-cgi (path or empty for default)"},
};